fragment PageParts on Page {
  __typename
  body
  sections {
    __typename
    title
    body
  }
}

fragment PostParts on Post {
  __typename
  title
  body
}

fragment NavParts on Nav {
  __typename
  title
  links {
    __typename
    title
    path
    sublinks {
      __typename
      title
      path
    }
  }
}

fragment StatisticsParts on Statistics {
  __typename
  body
  stat {
    __typename
    title
    column
    tooltip
    templates {
      __typename
      body
      threshold
    }
  }
  overview {
    __typename
    title
    column
    tooltip
    templates {
      __typename
      body
      threshold
    }
    measure
  }
}
